### ISSUE TITLE
Search Doesn't Work

### ISSUE THREAD

**Issue by spacebiscuit** [cnizzdotcom/cakephp-datatable#30]
Hi,

I have DataTables working with version 2.6 of Cake. But I cannot get the search to work. When I input a string I get an error and the XHR tab on my inspector says:

Model "Classified" is not associated with model "OR"

Also when I add 'link' to my paginate array I get an error but it works when I use 'contain' instead.

Also I couldn't find any instruction that mention that I had to add this to my routes:

Router::parseExtensions('json');

It might help others as it took me others to figure this out.

Thanks.

**Comment by spacebiscuit** [comment]
I've done some further testing, it seems that for search to work the 'Linkable' plugin is required, without it I get the error as reported above.

**Comment by cnizzdotcom** [comment]
Yes and honestly, containable kinda sucks anyways.

**Comment by spacebiscuit** [comment]
Thanks for the reply. I actually managed to get it working with Containable data as well as Linkable, the original error must have been in my syntax. I use this plugin in on all of my projects now, works very well and saves a lot of time and effort - many thanks!

**Comment by cnizzdotcom** [comment]
Nice, thanks spacebiscuit!
